version: "3.8"
services:
  database-browser_database:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  database-browser:
    build: .
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=test
      - MYSQL_URL=jdbc:mysql://mysql:3306/test
    depends_on:
      - database-browser_database
    restart: on-failure
    ports:
      - "8080:8080"
  database-browser_postgres:
    image: postgres
    restart: always
    hostname: postgre
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
